name: CodeMenuButton
description: A sample Polymer application
dependencies:
    polymer: ">=0.11.0-dev.2 <0.12.0"
    core_elements: any
transformers:
- polymer:
    entry_points: web/codemenubutton.html
